/**
 * The Alchemist's Quill — With OpenAI Integration
 * Conjured by Abiud Keter & Kimi
 */

// Fallback local transmutation (if AI fails)
const transmutations = {
  shakespeare: {
    greetings: {
      "hello": "Hail", "hi": "Hark", "hey": "Ho there",
      "good morning": "Good morrow", "how are you": "How fares thee",
      "thank you": "I give thee thanks", "please": "Prithee",
      "sorry": "I do beseech thy pardon", "yes": "Aye", "no": "Nay",
      "goodbye": "Farewell", "love": "love most true",
      "friend": "companion dear", "money": "coin", "work": "toil",
      "happy": "most glad", "sad": "heavy of heart", "angry": "wroth",
      "beautiful": "fair", "ugly": "ill-favored"
    },
    suffixes: ["— dost thou comprehend?", "— by my troth!", "— what sayest thou?", "— forsooth!"],
    prefixes: ["Hark! ", "Pray, ", "Mark me: ", "List! "]
  },
  victorian: {
    greetings: {
      "hello": "How do you do", "love": "affection most profound",
      "friend": "dearest acquaintance", "happy": "in good spirits",
      "sad": "rather low"
    },
    suffixes: ["— Most sincerely.", "— Your humble servant."],
    prefixes: ["I daresay ", "It is my understanding that "]
  },
  poe: {
    greetings: {
      "hello": "Dark greetings", "love": "obsession eternal",
      "happy": "fleeting moment of light", "sad": "abyssal despair"
    },
    suffixes: ["— nevermore.", "— in the shadows of the night."],
    prefixes: ["Once upon a midnight dreary, ", "In the bleak December, "]
  },
  romantic: {
    greetings: {
      "hello": "Dearest salutations", "love": "passion unbound",
      "happy": "swept by joy"
    },
    suffixes: ["— my heart swells!", "— forever thine."],
    prefixes: ["Oh! ", "My dearest, ", "In rapture, "]
  }
};

function transmuteText(text, style) {
  const patterns = transmutations[style];
  let result = text.toLowerCase();
  
  for (let [modern, archaic] of Object.entries(patterns.greetings)) {
    const regex = new RegExp(`\\b${modern}\\b`, 'gi');
    result = result.replace(regex, archaic);
  }
  
  const prefix = Math.random() > 0.7 ? patterns.prefixes[Math.floor(Math.random() * patterns.prefixes.length)] : "";
  const suffix = patterns.suffixes[Math.floor(Math.random() * patterns.suffixes.length)];
  
  result = result.charAt(0).toUpperCase() + result.slice(1);
  return prefix + result + suffix;
}

// NEW: OpenAI-powered transmutation
async function transmuteWithAI(text, style) {
  try {
    const response = await fetch('/api/transmute', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text, style })
    });

    const data = await response.json();

    if (!data.success) {
      throw new Error(data.error || 'Transmutation failed');
    }

    return data.transmuted;

  } catch (error) {
    console.error('AI Transmutation failed:', error);
    // Fallback to local
    return transmuteText(text, style);
  }
}

// Visual effects
function createInkDrop(x, y) {
  const drop = document.createElement('div');
  drop.className = 'ink-drop';
  drop.style.left = x + 'px';
  drop.style.top = y + 'px';
  document.body.appendChild(drop);
  setTimeout(() => drop.remove(), 1000);
}

function initAlchemicalSymbols() {
  const symbols = document.querySelectorAll('.alchemical-symbol');
  symbols.forEach(symbol => {
    symbol.addEventListener('mouseenter', () => {
      const colors = ['#8B4513', '#DAA520', '#CD853F', '#B8860B'];
      const randomColor = colors[Math.floor(Math.random() * colors.length)];
      symbol.style.textShadow = `0 0 30px ${randomColor}`;
    });
    symbol.addEventListener('mouseleave', () => {
      symbol.style.textShadow = '';
    });
  });
}

let ticking = false;
window.addEventListener('scroll', () => {
  if (!ticking) {
    window.requestAnimationFrame(() => {
      const scrolled = window.pageYOffset;
      document.querySelectorAll('.alchemical-symbol').forEach((symbol, index) => {
        symbol.style.transform = `translateY(${scrolled * (0.5 + index * 0.1)}px)`;
      });
      ticking = false;
    });
    ticking = true;
  }
});

// Main application
document.addEventListener('DOMContentLoaded', () => {
  // Remove candle loader
  const candle = document.getElementById('candleLoader');
  if (candle) setTimeout(() => candle.remove(), 3000);
  
  initAlchemicalSymbols();

  const transmuteBtn = document.getElementById('transmuteBtn');
  const modernInput = document.getElementById('modernInput');
  const styleSelect = document.getElementById('styleSelect');
  const outputSection = document.getElementById('outputSection');
  const outputText = document.getElementById('outputText');
  const styleLabel = document.getElementById('styleLabel');

  const styleNames = {
    shakespeare: "The Bard's Rendering (AI):",
    victorian: "The Gentleperson's Rendering (AI):",
    poe: "The Gothic Rendering (AI):",
    romantic: "The Lover's Rendering (AI):"
  };

  transmuteBtn.addEventListener('click', async (e) => {
    const input = modernInput.value.trim();
    if (!input) {
      alert("Prithee, enter some text first!");
      return;
    }

    // Loading state
    const originalText = transmuteBtn.textContent;
    transmuteBtn.textContent = 'Transmuting...';
    transmuteBtn.disabled = true;

    // Visual effect
    const rect = transmuteBtn.getBoundingClientRect();
    createInkDrop(rect.left + rect.width / 2, rect.top + rect.height / 2);

    const style = styleSelect.value;
    
    try {
      const transmuted = await transmuteWithAI(input, style);
      
      outputText.textContent = transmuted;
      styleLabel.textContent = styleNames[style];
      outputSection.style.display = 'block';
      outputSection.classList.add('revealed', 'quill-writing');
      
      setTimeout(() => outputSection.classList.remove('quill-writing'), 500);
      outputSection.scrollIntoView({ behavior: 'smooth', block: 'nearest' });

    } catch (error) {
      alert('The spirits are restless. Try again anon.');
      console.error(error);
    } finally {
      transmuteBtn.textContent = originalText;
      transmuteBtn.disabled = false;
    }
  });
});

// Utility functions
function copyText() {
  const text = document.getElementById('outputText').textContent;
  navigator.clipboard.writeText(text).then(() => alert("Copied to thy parchment!"));
}

function speakText() {
  const text = document.getElementById('outputText').textContent;
  const utterance = new SpeechSynthesisUtterance(text);
  utterance.rate = 0.8;
  utterance.pitch = 0.9;
  speechSynthesis.speak(utterance);
}

function shareText() {
  const text = document.getElementById('outputText').textContent;
  if (navigator.share) {
    navigator.share({ title: "The Alchemist's Quill", text, url: window.location.href });
  } else {
    window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`, '_blank');
  }
}

console.log("The Alchemist's Quill — Conjured by Abiud Keter & Kimi");
console.log('"We are such stuff as dreams are made on."');
        /**
 * The Alchemist's Quill — Expanded Literary Styles
 * Conjured by Abiud Keter & Kimi
 */

const transmutations = {
    shakespeare: {
        greetings: {
            "hello": "Hail",
            "hi": "Hark",
            "hey": "Ho there",
            "good morning": "Good morrow",
            "good day": "God give you good den",
            "good night": "Good e'en",
            "good evening": "Fair evening",
            "how are you": "How fares thee",
            "how do you do": "How now",
            "what's up": "What news",
            "thank you": "I give thee thanks",
            "thanks": "My thanks",
            "please": "Prithee",
            "sorry": "I do beseech thy pardon",
            "excuse me": "Anon, good sir",
            "pardon me": "I crave pardon",
            "yes": "Aye",
            "no": "Nay",
            "maybe": "Perchance",
            "perhaps": "Mayhap",
            "goodbye": "Farewell",
            "bye": "Adieu",
            "see you": "Till we meet again",
            "later": "Presently",
            "talk soon": "Commune anon",
            
            "love": "love most true",
            "like": "fancy",
            "adore": "dote upon",
            "hate": "abhor",
            "dislike": "mislike",
            
            "friend": "companion dear",
            "buddy": "comrade",
            "pal": "familiar",
            "enemy": "foe",
            "rival": "adversary",
            
            "man": "sirrah",
            "woman": "mistress",
            "lady": "milady",
            "lord": "milord",
            "gentleman": "goodman",
            "gentlewoman": "goodwife",
            "sir": "sirrah",
            "madam": "my lady",
            
            "king": "sire",
            "queen": "majesty",
            "prince": "princeling",
            "princess": "damsel",
            "knight": "cavalier",
            "noble": "peer",
            "servant": "varlet",
            "master": "liege",
            "slave": "bondman",
            
            "father": "sire",
            "mother": "dam",
            "dad": "sire",
            "mom": "dam",
            "brother": "frater",
            "sister": "soror",
            "son": "issue",
            "daughter": "maid",
            "child": "babe",
            "baby": "suckling",
            "boy": "lad",
            "girl": "lass",
            "kid": "youngling",
            "husband": "spouse",
            "wife": "matron",
            "bride": "betrothed",
            "groom": "suitor",
            
            "money": "coin",
            "cash": "ready money",
            "gold": "guilders",
            "silver": "sterling",
            "rich": "opulent",
            "wealthy": "of great substance",
            "poor": "destitute",
            "broke": "penniless",
            "expensive": "dear",
            "cheap": "of small price",
            
            "work": "toil",
            "job": "trade",
            "career": "vocation",
            "business": "affairs",
            "task": "charge",
            "duty": "office",
            "labor": "travail",
            
            "happy": "most glad",
            "glad": "joyful",
            "joyful": "blithe",
            "cheerful": "jocund",
            "merry": "festive",
            "sad": "heavy of heart",
            "unhappy": "discontent",
            "depressed": "melancholic",
            "angry": "wroth",
            "mad": "beside oneself",
            "furious": "incensed",
            "annoyed": "vexed",
            "irritated": "peevish",
            "calm": "serene",
            "peaceful": "tranquil",
            
            "crazy": "moon-struck",
            "insane": "distraught",
            "foolish": "witless",
            "stupid": "dull-witted",
            "dumb": "simple",
            "smart": "cunning",
            "clever": "subtle",
            "wise": "sage",
            "intelligent": "sharp-witted",
            
            "beautiful": "fair",
            "pretty": "comely",
            "lovely": "beauteous",
            "gorgeous": "ravishing",
            "handsome": "well-favored",
            "ugly": "ill-favored",
            "hideous": "monstrous",
            "plain": "homely",
            
            "good": "virtuous",
            "bad": "foul",
            "evil": "wicked",
            "kind": "gentle",
            "cruel": "ruthless",
            "brave": "valiant",
            "cowardly": "craven",
            "strong": "stout",
            "weak": "feeble",
            "powerful": "potent",
            "mighty": "puissant",
            
            "big": "gross",
            "large": "vast",
            "huge": "enormous",
            "great": "grand",
            "small": "wee",
            "little": "petty",
            "tiny": "minute",
            
            "old": "aged",
            "ancient": "of great years",
            "young": "green",
            "new": "fresh",
            "modern": "novel",
            
            "true": "veritable",
            "false": "counterfeit",
            "real": "authentic",
            "fake": "feigned",
            
            "clean": "undefiled",
            "dirty": "foul",
            "pure": "unmixed",
            "mixed": "mingled"
        },
                      nature: {
            "sun": "sol",
            "moon": "luna",
            "star": "stellar body",
            "sky": "firmament",
            "heaven": "empyrean",
            "cloud": "nimbus",
            "rain": "tempest",
            "storm": "tempest",
            "wind": "zephyr",
            "breeze": "gentle air",
            "snow": "snow",
            "ice": "ice",
            "fire": "blaze",
            "flame": "flare",
            "light": "glow",
            "dark": "dim",
            "shadow": "shade",
            "night": "night",
            "day": "day",
            "dawn": "aurora",
            "dusk": "gloaming",
            "morning": "morn",
            "evening": "eve",
            
            "earth": "terra",
            "ground": "soil",
            "land": "realm",
            "world": "globe",
            "universe": "cosmos",
            "sea": "brine",
            "ocean": "main",
            "lake": "mere",
            "river": "stream",
            "water": "aqua",
            "mountain": "peak",
            "hill": "knoll",
            "valley": "dale",
            "forest": "wood",
            "tree": "wood",
            "flower": "blossom",
            "rose": "rose",
            "grass": "turf",
            "garden": "orchard",
            
            "animal": "creature",
            "bird": "fowl",
            "dog": "hound",
            "cat": "mouser",
            "horse": "steed",
            "cow": "kine",
            "pig": "swine",
            "sheep": "mutton",
            "wolf": "wolf",
            "lion": "lion",
            "eagle": "erne",
            "fish": "fin",
            "snake": "serpent"
        },        actions: {
            "go": "wend",
            "come": "hie",
            "leave": "depart",
            "arrive": "reach",
            "enter": "penetrate",
            "exit": "egress",
            "sit": "be seated",
            "stand": "arise",
            "walk": "stride",
            "run": "hasten",
            "jump": "leap",
            "fall": "tumble",
            "rise": "ascend",
            "descend": "go down",
            
            "give": "bestow",
            "take": "seize",
            "get": "obtain",
            "have": "possess",
            "keep": "retain",
            "find": "discover",
            "lose": "forfeit",
            "win": "prevail",
            "fail": "miscarry",
            "succeed": "prosper",
            
            "make": "fashion",
            "build": "erect",
            "create": "forge",
            "destroy": "ruin",
            "break": "rend",
            "fix": "repair",
            "cut": "cleave",
            "join": "unite",
            "separate": "sunder",
            
            "kill": "slay",
            "die": "perish",
            "death": "demise",
            "life": "existence",
            "live": "dwell",
            "born": "begotten",
            "grow": "wax",
            "change": "alter",
            "become": "grow to be",
            
            "eat": "feed",
            "drink": "quaff",
            "sleep": "slumber",
            "wake": "awaken",
            "dream": "dream",
            "think": "ponder",
            "know": "wit",
            "learn": "study",
            "teach": "instruct",
            "read": "peruse",
            "write": "indite",
            "speak": "discourse",
            "talk": "converse",
            "say": "utter",
            "tell": "relate",
            "ask": "inquire",
            "answer": "respond",
            "call": "hail",
            "listen": "attend",
            "hear": "hark",
            "see": "behold",
            "watch": "observe",
            "look": "gaze",
            "find out": "ascertain",
            
            "want": "desire",
            "need": "require",
            "wish": "long",
            "hope": "trust",
            "fear": "dread",
            "worry": "vex",
            "care": "regard",
            
            "begin": "commence",
            "start": "originate",
            "end": "terminate",
            "finish": "complete",
            "stop": "cease",
            "continue": "proceed",
            "return": "come back",
            
            "help": "aid",
            "save": "preserve",
            "protect": "guard",
            "attack": "assail",
            "defend": "protect",
            "fight": "combat",
            "battle": "fray",
            "war": "strife",
            "peace": "accord",
            
            "use": "employ",
            "put": "place",
            "move": "stir",
            "turn": "wheel",
            "open": "unclose",
            "close": "shut",
            "hold": "grasp",
            "catch": "seize",
            "throw": "cast",
            "push": "thrust",
            "pull": "draw",
            "lift": "heave",
            "drop": "let fall",
            
            "pay": "render",
            "buy": "purchase",
            "sell": "vend",
            "send": "dispatch",
            "bring": "convey",
            "carry": "bear",
            
            "wash": "lave",
            "cook": "prepare",
            "clean": "make clean",
            "dress": "clothe",
            "wear": "bear",
            
            "count": "reckon",
            "measure": "mete",
            "judge": "deem",
            "believe": "credit",
            "trust": "rely",
            "remember": "bethink",
            "forget": "disremember",
            "understand": "comprehend",
            "agree": "concur",
            "disagree": "differ",
            
            "accept": "take",
            "refuse": "reject",
            "allow": "permit",
            "prevent": "hinder",
            "promise": "pledge",
            "swear": "vow",
            "threaten": "menace",
            "warn": "caution",
            "advise": "counsel",
            "encourage": "embolden",
            "discourage": "dismay",
            "praise": "commend",
            "blame": "censure",
            "insult": "affront",
            "compliment": "flatter",
            "thank": "give thanks",
            "welcome": "bid welcome",
            "celebrate": "observe",
            "mourn": "lament",
            
            "marry": "wed",
            "divorce": "put away",
            "meet": "encounter",
            "visit": "call upon",
            "invite": "bid",
            "join": "unite with",
            "separate": "part from",
            "include": "comprehend",
            "exclude": "shut out",
            
            "serve": "attend",
            "rule": "govern",
            "lead": "guide",
            "follow": "succeed",
            "obey": "be ruled by",
            "command": "bid",
            "order": "direct",
            "request": "sue for",
            "demand": "require",
            "offer": "tender",
            "suggest": "move",
            "recommend": "commend",
            "choose": "elect",
            "prefer": "rather",
            "compare": "liken",
            "match": "equal",
            "fit": "suit",
            "deserve": "merit",
            "earn": "win",
            
            "waste": "squander",
            "spend": "expend",
            "collect": "gather",
            "scatter": "disperse",
            "hide": "conceal",
            "search": "seek",
            "find out": "ascertain",
            "discover": "detect",
            "invent": "devise",
            "imagine": "conceive",
            "guess": "surmise",
            "wonder": "marvel",
            "surprise": "amaze",
            "shock": "appall",
            "please": "gratify",
            "displease": "offend",
            "satisfy": "content",
            "disappoint": "frustrate",
            "amuse": "divert",
            "bore": "weary",
            "tire": "fatigue",
            "excite": "stir",
            "calm": "quiet",
            "comfort": "console",
            "disturb": "trouble",
            
            "prepare": "make ready",
            "ready": "prepared",
            "complete": "finished",
            "perfect": "flawless",
            "improve": "ameliorate",
            "damage": "mar",
            "break": "rend",
            "repair": "mend",
            
            "try": "attempt",
            "test": "prove",
            "prove": "demonstrate",
            "show": "manifest",
            "hide": "secrete",
            "cover": "overspread",
            "uncover": "disclose",
            
            "burn": "consume",
            "freeze": "congeal",
            "melt": "liquefy",
            "boil": "seethe",
            "flow": "run",
            "fly": "soar",
            "swim": "float",
            "crawl": "creep",
            "climb": "scale",
            "sink": "founder",
            "float": "be buoyant",
            
            "bind": "tie",
            "loosen": "unbind",
            "rub": "chafe",
            "wipe": "dry",
            "polish": "burnish",
            
            "bite": "munch",
            "chew": "masticate",
            "smell": "scent",
            "taste": "savor",
            "touch": "feel",
            "feel": "perceive",
            
            "laugh": "guffaw",
            "cry": "weep",
            "smile": "grin",
            "frown": "scowl",
            "kiss": "buss",
            "hug": "embrace",
            "touch": "fondle"
        },
                                objects: {
            "house": "abode",
            "home": "hearth",
            "room": "chamber",
            "bed": "couch",
            "chair": "seat",
            "table": "board",
            "door": "portal",
            "window": "casement",
            "floor": "ground",
            "wall": "rampart",
            "roof": "thatch",
            "castle": "fortress",
            "tower": "turret",
            "prison": "dungeon",
            "church": "chapel",
            "temple": "fane",
            
            "book": "tome",
            "paper": "parchment",
            "pen": "quill",
            "ink": "gall",
            "letter": "epistle",
            "message": "tidings",
            "news": "intelligence",
            "story": "tale",
            "song": "lay",
            "poem": "verse",
            "music": "melody",
            "art": "craft",
            "play": "drama",
            "game": "sport",
            "toy": "bauble",
            
            "sword": "blade",
            "knife": "dagger",
            "spear": "lance",
            "shield": "buckler",
            "armor": "mail",
            "helmet": "casque",
            "bow": "bow",
            "arrow": "bolt",
            "gun": "piece",
            "weapon": "arm",
            
            "ship": "vessel",
            "boat": "bark",
            "carriage": "coach",
            "horse": "steed",
            "saddle": "pillion",
            
            "clothes": "raiment",
            "dress": "gown",
            "shirt": "doublet",
            "pants": "hose",
            "shoes": "shoon",
            "hat": "cap",
            "coat": "cloak",
            "ring": "band",
            "jewel": "gem",
            "gold": "gold",
            "silver": "silver",
            "crown": "coronet"
        },
        
        abstract: {
            "time": "tempus",
            "year": "twelvemonth",
            "month": "moon",
            "week": "se'nnight",
            "day": "day",
            "hour": "hour",
            "moment": "instant",
            "minute": "minute",
            "while": "whiles",
            "delay": "tarry",
            "wait": "bide",
            "haste": "post-haste",
            "soon": "ere long",
            "now": "anon",
            "then": "e'en now",
            "today": "this day",
            "tomorrow": "on the morrow",
            "yesterday": "yestereve",
            "always": "ever",
            "never": "ne'er",
            "often": "oft",
            "sometimes": "betimes",
            "again": "once more",
            "soon": "anon",
            "late": "belated",
            "early": "betimes",
            
            "word": "term",
            "name": "appellation",
            "title": "style",
            "voice": "tongue",
            "sound": "noise",
            "silence": "hush",
            "noise": "clamor",
            "music": "melody",
            "song": "lay",
            
            "mind": "intellect",
            "soul": "spirit",
            "heart": "bosom",
            "body": "corpse",
            "flesh": "meat",
            "blood": "gore",
            "bone": "skeleton",
            "life": "existence",
            "death": "demise",
            "birth": "nativity",
            
            "truth": "verity",
            "lie": "falsehood",
            "secret": "privity",
            "mystery": "enigma",
            "wonder": "marvel",
            "miracle": "portent",
            "magic": "sorcery",
            "spell": "charm",
            "curse": "malediction",
            "blessing": "benediction",
            "luck": "fortune",
            "fate": "destiny",
            "chance": "hap",
            "risk": "peril",
            "danger": "jeopardy",
            "safety": "security",
            
            "honor": "worship",
            "shame": "disgrace",
            "glory": "renown",
            "fame": "celebrity",
            "pride": "arrogance",
            "humility": "meekness",
            "courage": "valor",
            "cowardice": "pusillanimity",
            "virtue": "goodness",
            "vice": "wickedness",
            "sin": "transgression",
            "innocence": "guiltlessness",
            "guilt": "culpability",
            "justice": "equity",
            "mercy": "clemency",
            "revenge": "vengeance",
            "forgiveness": "pardon",
            
            "beauty": "comeliness",
            "ugliness": "deformity",
            "strength": "puissance",
            "weakness": "frailty",
            "health": "hale",
            "sickness": "malady",
            "pain": "anguish",
            "pleasure": "delight",
            "joy": "bliss",
            "grief": "sorrow",
            "anger": "ire",
            "fear": "dread",
            "hope": "expectation",
            "despair": "desperation",
            "love": "affection",
            "hate": "odium",
            "desire": "lust",
            "peace": "tranquility",
            "war": "hostility",
            
            "knowledge": "science",
            "wisdom": "sapience",
            "learning": "erudition",
            "ignorance": "nescience",
            "skill": "cunning",
            "art": "craft",
            "labor": "travail",
            "rest": "repose",
            "sleep": "slumber",
            "dream": "vision",
            
            "god": "Deity",
            "heaven": "paradise",
            "hell": "inferno",
            "angel": "seraph",
            "devil": "fiend",
            "soul": "psyche",
            "spirit": "ghost",
            "ghost": "specter",
            "witch": "sorceress",
            "wizard": "warlock",
            
            "country": "realm",
            "nation": "commonwealth",
            "kingdom": "dominion",
            "empire": "imperium",
            "city": "metropolis",
            "town": "borough",
            "village": "hamlet",
            "street": "lane",
            "road": "way",
            "path": "track",
            "bridge": "pont",
            "gate": "port",
            "wall": "rampart",
            "field": "lea",
            "farm": "grange",
            "garden": "orchard",
            "park": "mead",
            "forest": "wood",
            "wood": "grove",
            "meadow": "pasture",
            "river": "stream",
            "lake": "mere",
            "sea": "brine",
            "ocean": "main",
            "mountain": "mount",
            "hill": "knoll",
            "valley": "vale",
            "cave": "cavern",
            "rock": "stone",
            "stone": "pebble",
            "sand": "grit",
            "dust": "powder",
            "mud": "mire",
            "clay": "earth",
            "metal": "ore",
            "iron": "steel",
            "gold": "aurum",
            "silver": "argent",
            "copper": "brass",
            "wood": "timber",
            "tree": "stock",
            "leaf": "frond",
            "flower": "blossom",
            "root": "radicle",
            "branch": "bough",
            "fruit": "produce",
            "seed": "grain",
            "grass": "herb",
            "weed": "tare",
            "thorn": "spine",
            "rose": "rose",
            "lily": "lily",
            "oak": "oak",
            "pine": "fir",
            
            "bird": "fowl",
            "eagle": "erne",
            "hawk": "falcon",
            "owl": "mope",
            "crow": "raven",
            "dove": "pigeon",
            "swan": "swan",
            "goose": "gander",
            "duck": "drake",
            "chicken": "fowl",
            "hen": "pullet",
            "rooster": "cock",
            
            "fish": "fin",
            "shark": "dogfish",
            "whale": "leviathan",
            "snake": "serpent",
            "worm": "maggot",
            "fly": "gadfly",
            "bee": "honeybee",
            "spider": "arachnid",
            
            "horse": "steed",
            "mare": "jade",
            "stallion": "steed",
            "foal": "colt",
            "donkey": "ass",
            "mule": "mule",
            "ox": "bullock",
            "cow": "kine",
            "bull": "bull",
            "calf": "veal",
            "sheep": "mutton",
            "lamb": "lambkin",
            "goat": "kid",
            "pig": "swine",
            "hog": "boar",
            "dog": "hound",
            "hound": "brachet",
            "puppy": "whelp",
            "cat": "mouser",
            "kitten": "kitling",
            "wolf": "wolf",
            "fox": "tod",
            "bear": "bruin",
            "lion": "lion",
            "tiger": "tiger",
            "deer": "hart",
            "rabbit": "coney",
            "hare": "leveret",
            "rat": "rat",
            "mouse": "mouse",
            
            "food": "viands",
            "meal": "repast",
            "feast": "banquet",
            "dish": "plate",
            "bread": "loaf",
            "meat": "flesh",
            "beef": "boeuf",
            "pork": "porc",
            "mutton": "mutton",
            "venison": "venison",
            "fish": "fin",
            "egg": "eyren",
            "milk": "lacteal",
            "cheese": "fromage",
            "butter": "butter",
            "wine": "sack",
            "beer": "ale",
            "water": "aqua",
            "drink": "libation",
            
            "clothes": "raiment",
            "shirt": "doublet",
            "coat": "cloak",
            "dress": "gown",
            "skirt": "kirtle",
            "pants": "hose",
            "shoes": "shoon",
            "boots": "buskins",
            "hat": "cap",
            "cap": "coif",
            "glove": "gauntlet",
            "ring": "band",
            "necklace": "chain",
            "crown": "coronet",
            "armor": "mail",
            "helmet": "casque",
            "shield": "buckler",
            
            "sword": "blade",
            "dagger": "poniard",
            "knife": "whittle",
            "spear": "lance",
            "bow": "bow",
            "arrow": "bolt",
            "gun": "piece",
            "cannon": "gun",
            
            "ship": "vessel",
            "boat": "bark",
            "sail": "canvas",
            "oar": "paddle",
            "anchor": "grapnel",
            "port": "haven",
            "harbor": "haven",
            
            "book": "tome",
            "page": "leaf",
            "paper": "parchment",
            "pen": "quill",
            "ink": "gall",
            "letter": "epistle",
            "writing": "script",
            "reading": "perusal",
            "study": "meditation",
            "school": "academy",
            "teacher": "pedagogue",
            "student": "pupil",
            "lesson": "lecture",
            "knowledge": "science",
            "wisdom": "sapience",
            "truth": "verity",
            "lie": "falsity",
            "secret": "privity",
            "mystery": "enigma",
            "magic": "necromancy",
            "spell": "incantation",
            "witchcraft": "sorcery",
            "alchemy": "hermetic art",
            
            "money": "coin",
            "gold": "aurum",
            "silver": "argent",
            "copper": "brass",
            "coin": "piece",
            "treasure": "hoard",
            "wealth": "substance",
            "poverty": "indigence",
            "rich": "opulent",
            "poor": "destitute",
            
            "work": "toil",
            "labor": "travail",
            "task": "charge",
            "duty": "office",
            "job": "employment",
            "trade": "craft",
            "business": "affairs",
            "profit": "gain",
            "loss": "detriment",
            "debt": "obligation",
            "payment": "reckoning",
            "price": "cost",
            "value": "worth",
            "cheap": "of small price",
            "dear": "expensive",
            
            "friend": "companion",
            "enemy": "adversary",
            "stranger": "foreigner",
            "guest": "visitant",
            "host": "entertainer",
            "neighbor": "borderer",
            "servant": "attendant",
            "master": "lord",
            "slave": "thrall",
            "prisoner": "captive",
            "criminal": "malefactor",
            "judge": "justice",
            "lawyer": "advocate",
            "doctor": "physician",
            "priest": "clerk",
            "soldier": "warrior",
            "sailor": "mariner",
            "farmer": "husbandman",
            "merchant": "tradesman",
            "craftsman": "artificer",
            "artist": "artisan",
            "musician": "minstrel",
            "actor": "player",
            "writer": "penman",
            "poet": "bard",
            "king": "monarch",
            "queen": "consort",
            "prince": "heir",
            "princess": "damsel",
            "noble": "peer",
            "knight": "cavalier",
            "lady": "dame",
            "lord": "seigneur",
            
            "father": "sire",
            "mother": "dam",
            "parent": "progenitor",
            "child": "offspring",
            "son": "issue",
            "daughter": "maid",
            "brother": "frater",
            "sister": "soror",
            "husband": "spouse",
            "wife": "matron",
            "bride": "betrothed",
            "groom": "suitor",
            "baby": "babe",
            "boy": "lad",
            "girl": "lass",
            "youth": "stripling",
            "maiden": "damsel",
            "old man": "graybeard",
            "old woman": "beldam"
        },
        
        suffixes: [
            "— dost thou comprehend?",
            "— pray, tell me true.",
            "— by my troth!",
            "— what sayest thou?",
            "— forsooth!",
            "— verily!",
            "— in sooth!",
            "— marry!",
            "— indeed!",
            "— in faith!",
            "— on my honor!",
            "— as I live!",
            "— upon my word!",
            "— as I am a gentleman!",
            "— as I am a true man!",
            "— so help me Heaven!",
            "— by the mass!",
            "— by our Lady!",
            "— God's blessing on thy heart!",
            "— fare thee well!",
            "— adieu, good friend!",
            "— till we meet again!",
            "— God be with thee!",
            "— Heaven prosper thee!",
            "— the gods be good to thee!",
            "— may Fortune smile upon thee!",
            "— all's well that ends well!",
            "— the play's the thing!",
            "— to thine own self be true!",
            "— though she be but little, she is fierce!",
            "— parting is such sweet sorrow!",
            "— the course of true love never did run smooth!",
            "— all the world's a stage!",
            "— we are such stuff as dreams are made on!",
            "— the readiness is all!",
            "— the rest is silence!",
            "— good night, good night!",
            "— sweet dreams be thine!",
            "— God give thee joy!",
            "— much ado about nothing!",
            "— measure for measure!",
            "— love's labour's won!",
            "— a midsummer night's dream!",
            "— the winter's tale!",
            "— the tempest!",
            "— as you like it!",
            "— twelfth night!",
            "— the merchant of Venice!",
            "— Romeo and Juliet!",
            "— Hamlet!",
            "— Macbeth!",
            "— King Lear!",
            "— Othello!",
            "— Antony and Cleopatra!",
            "— Julius Caesar!",
            "— the comedy of errors!",
            "— Titus Andronicus!",
            "— the two gentlemen of Verona!",
            "— the taming of the shrew!",
            "— the merry wives of Windsor!",
            "— much ado about nothing!",
            "— all's well that ends well!",
            "— measure for measure!",
            "— the tragedy of Coriolanus!",
            "— Timon of Athens!",
            "— Pericles, Prince of Tyre!",
            "— Cymbeline!",
            "— the two noble kinsmen!"
        ],
        
        prefixes: [
            "Hark! ",
            "O! ",
            "Pray, ",
            "Mark me: ",
            "List! ",
            "Anon, ",
            "Hearken, ",
            "Attend, ",
            "Lo! ",
            "Behold! ",
            "Fie! ",
            "Zounds! ",
            "S'blood! ",
            "Marry, ",
            "In truth, ",
            "In sooth, ",
            "Forsooth, ",
            "Verily, ",
            "In faith, ",
            "By my troth, ",
            "Upon my word, ",
            "As I live, ",
            "Before my eyes, ",
            "On my life, ",
            "As I am true man, ",
            "God's blessing on thee, ",
            "Good morrow to thee, ",
            "Well met, ",
            "Give ear, ",
            "Lend me thy ears, ",
            "O happy day! ",
            "What light through yonder window breaks! ",
            "To be or not to be, ",
            "Alas, poor Yorick! ",
            "Et tu, Brute? ",
            "The lady doth protest too much, ",
            "Though she be but little, she is fierce! ",
            "The course of true love never did run smooth, ",
            "All the world's a stage, ",
            "The readiness is all, ",
            "Now is the winter of our discontent, ",
            "A horse! a horse! my kingdom for a horse! ",
            "Once more unto the breach, dear friends, ",
            "We few, we happy few, we band of brothers, ",
            "Cry 'Havoc!', and let slip the dogs of war, ",
            "The evil that men do lives after them, ",
            "The good is oft interred with their bones, ",
            "Friends, Romans, countrymen, lend me your ears, ",
            "The fault, dear Brutus, is not in our stars, ",
            "But in ourselves, that we are underlings, ",
            "Brevity is the soul of wit, ",
            "There are more things in heaven and earth, Horatio, ",
            "Than are dreamt of in your philosophy, ",
            "Something is rotten in the state of Denmark, ",
            "The lady doth protest too much, methinks, ",
            "O brave new world, ",
            "That has such people in't! ",
            "Hell is empty, ",
            "And all the devils are here, ",
            "Love looks not with the eyes, but with the mind, ",
            "And therefore is winged Cupid painted blind, ",
            "The fool doth think he is wise, ",
            "But the wise man knows himself to be a fool, ",
            "Lord, what fools these mortals be! ",
            "I am not bound to please thee with my answers, ",
            "My tongue will tell the anger of my heart, ",
            "Or else my heart concealing it will break, ",
            "I had rather hear my dog bark at a crow, ",
            "Than a man swear he loves me, ",
            "I do love nothing in the world so well as you, ",
            "Is not that strange? ",
            "I would not wish any companion in the world but you, ",
            "Let me not to the marriage of true minds admit impediments, ",
            "Love is not love which alters when it alteration finds, ",
            "Or bends with the remover to remove, ",
            "O no! it is an ever-fixed mark, ",
            "That looks on tempests and is never shaken, ",
            "Shall I compare thee to a summer's day? ",
            "Thou art more lovely and more temperate, ",
            "Rough winds do shake the darling buds of May, ",
            "And summer's lease hath all too short a date, ",
            "When in disgrace with fortune and men's eyes, ",
         victorian: {
        greetings: {
            "hello": "How do you do",
            "hi": "I bid you good day",
            "hey": "I say",
            "good morning": "A very good morning to you",
            "good day": "A pleasant day to you",
            "good evening": "Good evening",
            "good night": "Pleasant dreams",
            "how are you": "How do you find yourself",
            "how do you do": "How do you do",
            "what's up": "What is the news",
            "thank you": "I am much obliged",
            "thanks": "My sincere thanks",
            "please": "If you please",
            "sorry": "I beg your pardon",
            "excuse me": "Pardon my intrusion",
            "pardon me": "I crave forgiveness",
            "yes": "Indeed",
            "no": "Not at all",
            "maybe": "Possibly",
            "perhaps": "Peradventure",
            "goodbye": "I wish you a very good day",
            "bye": "Au revoir",
            "see you": "Until we meet again",
            "later": "At your earliest convenience",
            "talk soon": "I shall correspond with you shortly",
            
            "love": "affection most profound",
            "like": "esteem",
            "adore": "hold in the highest regard",
            "hate": "regard with extreme disfavor",
            "dislike": "find disagreeable",
            
            "friend": "dearest acquaintance",
            "buddy": "companion",
            "pal": "intimate associate",
            "enemy": "adversary",
            "rival": "competitor",
            
            "man": "gentleman",
            "woman": "lady",
            "lady": "lady",
            "lord": "lord",
            "gentleman": "gentleman",
            "gentlewoman": "gentlewoman",
            "sir": "sir",
            "madam": "madam",
            
            "king": "His Majesty",
            "queen": "Her Majesty",
            "prince": "His Royal Highness",
            "princess": "Her Royal Highness",
            "noble": "person of quality",
            
            "father": "paterfamilias",
            "mother": "materfamilias",
            "dad": "father",
            "mom": "mother",
            "brother": "fraternal relation",
            "sister": "sororal relation",
            "son": "male offspring",
            "daughter": "female offspring",
            "child": "progeny",
            "baby": "infant",
            "boy": "young lad",
            "girl": "young lady",
            "kid": "juvenile",
            "husband": "spouse",
            "wife": "consort",
            "bride": "betrothed",
            "groom": "intended",
            
            "money": "pecuniary resources",
            "cash": "ready funds",
            "gold": "specie",
            "rich": "of independent means",
            "wealthy": "in comfortable circumstances",
            "poor": "in reduced circumstances",
            "broke": "embarrassed financially",
            "expensive": "costly",
            "cheap": "economical",
            
            "work": "occupation",
            "job": "situation",
            "career": "profession",
            "business": "concerns",
            "task": "undertaking",
            "duty": "responsibility",
            "labor": "exertion",
            
            "happy": "in good spirits",
            "glad": "pleased",
            "joyful": "delighted",
            "cheerful": "in fine fettle",
            "merry": "jovial",
            "sad": "rather low",
            "unhappy": "out of sorts",
            "depressed": "in the dismals",
            "angry": "out of temper",
            "mad": "indignant",
            "furious": "in high dudgeon",
            "annoyed": "vexed",
            "irritated": "put out",
            "calm": "composed",
            "peaceful": "tranquil",
            
            "crazy": "touched",
            "insane": "non compos mentis",
            "foolish": "unwise",
            "stupid": "obtuse",
            "dumb": "simple-minded",
            "smart": "clever",
            "clever": "astute",
            "wise": "sage",
            "intelligent": "of sound understanding",
            
            "beautiful": "quite becoming",
            "pretty": "pleasing to the eye",
            "lovely": "charming",
            "gorgeous": "splendid",
            "handsome": "well-looking",
            "ugly": "unfortunate in appearance",
            "hideous": "shocking to the sensibilities",
            "plain": "unremarkable",
            
            "good": "proper",
            "bad": "improper",
            "evil": "wicked",
            "kind": "benevolent",
            "cruel": "unkind",
            "brave": "courageous",
            "cowardly": "lacking in spirit",
            "strong": "robust",
            "weak": "delicate",
            "powerful": "influential",
            "mighty": "formidable",
            
            "big": "substantial",
            "large": "considerable",
            "huge": "enormous",
            "great": "significant",
            "small": "modest",
            "little": "diminutive",
            "tiny": "minute",
            
            "old": "elderly",
            "ancient": "of advanced years",
            "young": "youthful",
            "new": "novel",
            "modern": "contemporary",
            
            "true": "veritable",
            "false": "spurious",
            "real": "genuine",
            "fake": "counterfeit",
            
            "clean": "spotless",
            "dirty": "soiled",
            "pure": "unsullied",
            "mixed": "adulterated"
        },
        
        nature: {
            "sun": "solar orb",
            "moon": "lunar body",
            "star": "heavenly body",
            "sky": "firmament",
            "heaven": "celestial realm",
            "cloud": "vapor",
            "rain": "precipitation",
            "storm": "tempest",
            "wind": "current of air",
            "breeze": "gentle zephyr",
            "snow": "frozen precipitation",
            "ice": "congealed water",
            "fire": "conflagration",
            "flame": "blaze",
            "light": "illumination",
            "dark": "absence of light",
            "shadow": "shade",
            "night": "nocturnal hours",
            "day": "diurnal period",
            "dawn": "aurora",
            "dusk": "vesper",
            "morning": "matutinal hours",
            "evening": "eventide",
            
            "earth": "terrestrial sphere",
            "ground": "terra firma",
            "land": "country",
            "world": "globe",
            "universe": "cosmos",
            "sea": "ocean",
            "ocean": "briny deep",
            "lake": "sheet of water",
            "river": "stream",
            "water": "aqua",
            "mountain": "elevated landform",
            "hill": "eminence",
            "valley": "dale",
            "forest": "woodland",
            "tree": "arbor",
            "flower": "blossom",
            "rose": "queen of flowers",
            "grass": "turf",
            "garden": "pleasure ground",
            
            "animal": "creature",
            "bird": "feathered creature",
            "dog": "canine",
            "cat": "feline",
            "horse": "equine",
            "cow": "bovine",
            "pig": "porcine",
            "sheep": "ovine"
        },
        
        actions: {
            "go": "proceed",
            "come": "arrive",
            "leave": "take one's departure",
            "arrive": "make one's appearance",
            "enter": "gain admittance",
            "exit": "make one's exit",
            "sit": "take a seat",
            "stand": "rise",
            "walk": "perambulate",
            "run": "hasten",
            "jump": "spring",
            "fall": "suffer a descent",
            "rise": "ascend",
            "descend": "go down",
            
            "give": "bestow",
            "take": "receive",
            "get": "obtain",
            "have": "possess",
            "keep": "retain",
            "find": "discover",
            "lose": "misplace",
            "win": "achieve victory",
            "fail": "meet with disappointment",
            "succeed": "attain one's object",
            
            "make": "manufacture",
            "build": "construct",
            "create": "produce",
            "destroy": "demolish",
            "break": "fracture",
            "fix": "repair",
            "cut": "sever",
            "join": "unite",
            "separate": "disjoin",
            
            "kill": "deprive of life",
            "die": "expire",
            "death": "decease",
            "life": "existence",
            "live": "reside",
            "born": "come into the world",
            "grow": "increase in stature",
            "change": "alter",
            "become": "grow to be",
            
            "eat": "partake of nourishment",
            "drink": "imbibe",
            "sleep": "repose",
            "wake": "awaken",
            "dream": "have visions",
            "think": "reflect",
            "know": "be aware",
            "learn": "acquire knowledge",
            "teach": "impart instruction",
            "read": "peruse",
            "write": "indite",
            "speak": "discourse",
            "talk": "converse",
            "say": "utter",
            "tell": "relate",
            "ask": "inquire",
            "answer": "reply",
            "call": "summon",
            "listen": "give ear",
            "hear": "hearken",
            "see": "behold",
            "watch": "observe",
            "look": "regard",
            "find out": "ascertain",
            
            "want": "desire",
            "need": "require",
            "wish": "long for",
            "hope": "anticipate",
            "fear": "apprehend",
            "worry": "feel anxiety",
            "care": "regard",
            
            "begin": "commence",
            "start": "initiate",
            "end": "terminate",
            "finish": "complete",
            "stop": "cease",
            "continue": "proceed",
            "return": "come back",
            
            "help": "assist",
            "save": "preserve",
            "protect": "guard",
            "attack": "assail",
            "defend": "protect",
            "fight": "contend",
            "battle": "engagement",
            "war": "hostilities",
            "peace": "tranquility",
            
            "use": "employ",
            "put": "place",
            "move": "stir",
            "turn": "rotate",
            "open": "unclose",
            "close": "shut",
            "hold": "grasp",
            "catch": "seize",
            "throw": "cast",
            "push": "thrust",
            "pull": "draw",
            "lift": "raise",
            "drop": "let fall",
            
            "pay": "disburse",
            "buy": "purchase",
            "sell": "dispose of",
            "send": "dispatch",
            "bring": "convey",
            "carry": "bear",
            
            "wash": "cleanse",
            "cook": "prepare",
            "clean": "make clean",
            "dress": "clothe",
            "wear": "have on",
            
            "count": "enumerate",
            "measure": "gauge",
            "judge": "form an opinion",
            "believe": "credit",
            "trust": "confide in",
            "remember": "recollect",
            "forget": "fail to remember",
            "understand": "comprehend",
            "agree": "concur",
            "disagree": "differ",
            
            "accept": "receive",
            "refuse": "decline",
            "allow": "permit",
            "prevent": "hinder",
            "promise": "pledge",
            "swear": "take an oath",
            "threaten": "menace",
            "warn": "caution",
            "advise": "counsel",
            "encourage": "embolden",
            "discourage": "dismay",
            "praise": "commend",
            "blame": "censure",
            "insult": "affront",
            "compliment": "flatter",
            "thank": "express gratitude",
            "welcome": "receive graciously",
            "celebrate": "observe",
            "mourn": "lament",
            
            "marry": "wed",
            "divorce": "obtain a dissolution of marriage",
            "meet": "encounter",
            "visit": "call upon",
            "invite": "request the presence of",
            "join": "unite with",
            "separate": "part from",
            "include": "comprehend",
            "exclude": "shut out",
            
            "serve": "attend",
            "rule": "govern",
            "lead": "guide",
            "follow": "succeed",
            "obey": "be ruled by",
            "command": "order",
            "order": "direct",
            "request": "solicit",
            "demand": "require",
            "offer": "proffer",
            "suggest": "propose",
            "recommend": "advise",
            "choose": "select",
            "prefer": "have a preference for",
            "compare": "draw a comparison",
            "match": "equal",
            "fit": "suit",
            "deserve": "merit",
            "earn": "win",
            
            "waste": "squander",
            "spend": "expend",
            "collect": "gather",
            "scatter": "disperse",
            "hide": "conceal",
            "search": "seek",
            "find out": "ascertain",
            "discover": "detect",
            "invent": "devise",
            "imagine": "conceive",
            "guess": "surmise",
            "wonder": "marvel",
            "surprise": "astonish",
            "shock": "appall",
            "please": "gratify",
            "displease": "offend",
            "satisfy": "content",
            "disappoint": "frustrate",
            "amuse": "divert",
            "bore": "weary",
            "tire": "fatigue",
            "excite": "stir",
            "calm": "quiet",
            "comfort": "console",
            "disturb": "trouble",
            
            "prepare": "make ready",
            "ready": "prepared",
            "complete": "finished",
            "perfect": "flawless",
            "improve": "ameliorate",
            "damage": "injure",
            "break": "rend",
            "repair": "mend",
            
            "try": "attempt",
            "test": "prove",
            "prove": "demonstrate",
            "show": "manifest",
            "hide": "secrete",
            "cover": "overspread",
            "uncover": "disclose",
            
            "burn": "consume",
            "freeze": "congeal",
            "melt": "liquefy",
            "boil": "seethe",
            "flow": "run",
            "fly": "soar",
            "swim": "float",
            "crawl": "creep",
            "climb": "scale",
            "sink": "founder",
            "float": "be buoyant",
            
            "bind": "tie",
            "loosen": "unbind",
            "rub": "chafe",
            "wipe": "dry",
            "polish": "burnish",
            
            "bite": "munch",
            "chew": "masticate",
            "smell": "scent",
            "taste": "savor",
            "touch": "feel",
            "feel": "perceive",
            
            "laugh": "express amusement",
            "cry": "weep",
            "smile": "grin",
            "frown": "scowl",
            "kiss": "salute",
            "hug": "embrace",
            "touch": "fondle"
        },
        
        objects: {
            "house": "residence",
            "home": "domicile",
            "room": "apartment",
            "bed": "couch",
            "chair": "seat",
            "table": "board",
            "door": "portal",
            "window": "casement",
            "floor": "ground",
            "wall": "partition",
            "roof": "covering",
            "castle": "fortress",
            "tower": "turret",
            "prison": "gaol",
            "church": "chapel",
            "temple": "fane",
            
            "book": "volume",
            "paper": "folio",
            "pen": "writing instrument",
            "ink": "fluid",
            "letter": "epistle",
            "message": "communication",
            "news": "intelligence",
            "story": "narrative",
            "song": "melody",
            "poem": "verse",
            "music": "harmony",
            "art": "fine art",
            "play": "drama",
            "game": "pastime",
            "toy": "plaything",
            
            "sword": "blade",
            "knife": "cutting instrument",
            "spear": "lance",
            "shield": "buckler",
            "armor": "mail",
            "helmet": "headpiece",
            "bow": "bow",
            "arrow": "shaft",
            "gun": "firearm",
            "weapon": "arm",
            
            "ship": "vessel",
            "boat": "craft",
            "carriage": "conveyance",
            "horse": "equine",
            "saddle": "seat",
            
            "clothes": "raiment",
            "dress": "gown",
            "shirt": "garment",
            "pants": "trousers",
            "shoes": "footwear",
            "hat": "head covering",
            "coat": "outer garment",
            "ring": "band",
            "jewel": "gem",
            "gold": "precious metal",
            "silver": "noble metal",
            "crown": "coronet"
        },
        
        abstract: {
            "time": "duration",
            "year": "twelvemonth",
            "month": "lunar period",
            "week": "se'nnight",
            "day": "solar day",
            "hour": "sixty minutes",
            "moment": "instant",
            "minute": "sixty seconds",
            "while": "space of time",
            "delay": "postponement",
            "wait": "expectation",
            "haste": "celerity",
            "soon": "ere long",
            "now": "at present",
            "then": "at that time",
            "today": "this day",
            "tomorrow": "on the morrow",
            "yesterday": "yestereve",
            "always": "at all times",
            "never": "at no time",
            "often": "frequently",
            "sometimes": "occasionally",
            "again": "once more",
            "late": "belated",
            "early": "betimes",
            
            "word": "term",
            "name": "appellation",
            "title": "designation",
            "voice": "utterance",
            "sound": "auditory sensation",
            "silence": "absence of sound",
            "noise": "clamor",
            "music": "harmony",
            "song": "melody",
            
            "mind": "intellect",
            "soul": "spirit",
            "heart": "bosom",
            "body": "corporeal frame",
            "flesh": "meat",
            "blood": "vital fluid",
            "bone": "osseous substance",
            "life": "existence",
            "death": "decease",
            "birth": "nativity",
            
            "truth": "verity",
            "lie": "falsehood",
            "secret": "confidential matter",
            "mystery": "enigma",
            "wonder": "marvel",
            "miracle": "portent",
            "magic": "prestidigitation",
            "spell": "charm",
            "curse": "imprecation",
            "blessing": "benediction",
            "luck": "fortune",
            "fate": "destiny",
            "chance": "hap",
            "risk": "peril",
            "danger": "jeopardy",
            "safety": "security",
            
            "honor": "integrity",
            "shame": "disgrace",
            "glory": "renown",
            "fame": "celebrity",
            "pride": "self-esteem",
            "humility": "meekness",
                    suffixes: [
            "— I remain, etc.",
            "— Most sincerely.",
            "— Your humble servant.",
            "— With profound respect.",
            "— I have the honor to be.",
            "— Believe me, yours faithfully.",
            "— Pray accept my best wishes.",
            "— I beg to remain.",
            "— At your service.",
            "— With great esteem.",
            "— Your obliged and obedient servant.",
            "— I am, dear sir, yours truly.",
            "— Allow me to subscribe myself.",
            "— I remain, dear madam, your affectionate friend.",
            "— With every kind wish.",
            "— Pray present my compliments.",
            "— I beg to assure you of my highest consideration.",
            "— With sentiments of profound respect.",
            "— I am, very truly, yours.",
            "— Believe me, ever yours.",
            "— I remain, with great respect, yours obediently.",
            "— Pray excuse the liberty I take.",
            "— I trust I do not presume too far.",
            "— With every sentiment of regard.",
            "— I am, my dear sir, ever faithfully yours.",
            "— I remain, dear madam, most sincerely yours.",
            "— With the greatest respect.",
            "— I beg you will accept my apologies.",
            "— Pray forgive this intrusion.",
            "— I remain, yours to command.",
            "— With every consideration.",
            "— I am, sir, your most obliged.",
            "— Believe me, my dear friend, ever affectionately yours.",
            "— I remain, with sincere regard, yours truly.",
            "— Pray allow me to express my gratitude.",
            "— With every feeling of respect and esteem.",
            "— I beg to remain, your most obedient servant.",
            "— I am, dear sir, with profound respect, yours.",
            "— Believe me, yours very sincerely.",
            "— I remain, yours faithfully and obliged.",
            "— With every sentiment of gratitude and respect.",
            "— Pray accept my assurances of high consideration.",
            "— I am, very respectfully, your obedient servant.",
            "— I remain, with every good wish, yours sincerely.",
            "— Believe me, ever your faithful friend.",
            "— I beg to remain, with great respect, yours truly.",
            "— With every feeling of sincere regard.",
            "— I am, dear madam, your most devoted servant.",
            "— Pray excuse this hurried note.",
            "— I remain, in great haste, yours faithfully.",
            "— With every apology for this liberty.",
            "— Believe me, yours with great esteem.",
            "— I beg to remain, your most grateful servant.",
            "— I am, sir, with every consideration, yours.",
            "— Pray accept my renewed assurances of respect.",
            "— I remain, dear sir, most respectfully yours.",
            "— With every sentiment of profound gratitude.",
            "— Believe me, ever affectionately yours.",
            "— I beg to remain, with sincere respect, yours obediently.",
            "— I am, very truly, your faithful servant.",
            "— Pray forgive this apparent presumption.",
            "— I remain, with every good wish, yours truly.",
            "— With every feeling of grateful respect.",
            "— Believe me, my dear sir, yours most sincerely.",
            "— I beg to remain, your obliged and faithful friend.",
            "— I am, dear madam, with profound regard, yours.",
            "— Pray accept my best thanks for your kindness.",
            "— I remain, in all sincerity, yours faithfully.",
            "— With every sentiment of devoted respect.",
            "— Believe me, ever your grateful and obliged servant.",
            "— I beg to remain, with the greatest esteem, yours.",
            "— I am, sir, your most respectful and obedient servant.",
            "— Pray excuse this informal communication.",
            "— I remain, with every consideration, yours sincerely.",
            "— With every feeling of sincere gratitude and respect.",
            "— Believe me, dear friend, ever faithfully yours.",
            "— I beg to remain, your most devoted and obliged servant.",
            "— I am, very respectfully and sincerely, yours.",
            "— Pray accept my renewed expressions of esteem.",
            "— I remain, with every sentiment of regard, yours truly.",
            "— With every apology for troubling you thus.",
            "— Believe me, yours with the greatest respect.",
            "— I beg to remain, in all gratitude, your faithful servant.",
            "— I am, dear sir, with every consideration, yours truly.",
            "— Pray forgive this lengthy epistle.",
            "— I remain, with every good wish, your obliged friend.",
            "— With every feeling of profound respect and attachment.",
            "— Believe me, ever your affectionate and devoted friend.",
            "— I beg to remain, with sincere gratitude, yours obediently.",
            "— I am, sir, your most respectful and grateful servant.",
            "— Pray accept my assurances of continued regard.",
            "— I remain, in great sincerity, yours faithfully.",
            "— With every sentiment of respectful admiration.",
            "— Believe me, dear madam, yours most devotedly.",
            "— I beg to remain, your ever grateful and obliged servant.",
            "— I am, with every consideration, your faithful friend.",
            "— Pray excuse this apparent forwardness.",
            "— I remain, with every feeling of esteem, yours truly.",
            "— With every apology for this unsolicited address.",
            "— Believe me, ever your respectful and obliged servant.",
            "— I beg to remain, with profound gratitude, yours sincerely.",
            "— I am, dear sir, in all respect, your obedient servant.",
            "— Pray accept my humble thanks for your attention.",
            "— I remain, with every sentiment of grateful regard, yours.",
            "— With every feeling of sincere respect and friendship.",
            "— Believe me, my dear friend, ever yours with affection.",
            "— I beg to remain, your most respectful and devoted servant.",
            "— I am, very truly and sincerely, your obliged friend.",
            "— Pray forgive this liberty I have taken.",
            "— I remain, with every good wish, yours faithfully and obliged.",
            "— With every sentiment of profound esteem and gratitude.",
            "— Believe me, ever your faithful and affectionate servant.",
            "— I beg to remain, with great respect and gratitude, yours.",
            "— I am, dear madam, with every consideration, your devoted servant.",
            "— Pray accept my renewed thanks for your kindness.",
            "— I remain, in all sincerity and respect, yours truly.",
            "— With every feeling of grateful and respectful regard.",
            "— Believe me, dear sir, yours ever faithfully and obliged.",
            "— I beg to remain, your most grateful and respectful servant.",
            "— I am, with profound respect, your obedient and faithful friend.",
            "— Pray excuse this intrusion upon your valuable time.",
            "— I remain, with every sentiment of sincere gratitude, yours.",
            "— With every apology for this apparent presumption.",
            "— Believe me, ever your respectful, grateful, and devoted servant.",
            "— I beg to remain, in all esteem and regard, yours faithfully.",
            "— I am, dear sir, with every good wish, your most obliged servant.",
            "— Pray accept my humble acknowledgments of your favor.",
            "— I remain, with every feeling of profound respect, yours truly.",
            "— With every sentiment of affectionate gratitude and esteem.",
            "— Believe me, my dear friend, ever yours with sincere regard.",
            "— I beg to remain, your most devoted, grateful, and obliged servant.",
            "— I am, very respectfully, sincerely, and truly, yours.",
            "— Pray forgive this apparent liberty I have presumed to take.",
            "— I remain, with every consideration and good wish, yours faithfully.",
            "— With every feeling of respectful, grateful, and sincere regard.",
            "— Believe me, ever your affectionate, faithful, and devoted friend.",
            "— I beg to remain, with profound respect and gratitude, yours obediently.",
            "— I am, dear madam, with every sentiment of esteem, your devoted servant.",
            "— Pray accept my renewed and heartfelt thanks.",
            "— I remain, in all sincerity, respect, and gratitude, yours truly.",
            "— With every apology for this lengthy and perhaps tedious communication.",
            "— Believe me, dear sir, ever yours with the greatest respect and esteem.",
            "— I beg to remain, your most respectful, grateful, and faithful servant.",
            "— I am, with every consideration and good wish, your obliged and faithful friend.",
            "— Pray excuse this apparent intrusion upon your privacy and time.",
            "— I remain, with every sentiment of profound regard, yours sincerely and faithfully.",
            "— With every feeling of sincere gratitude, respect, and affectionate regard.",
            "— Believe me, ever your devoted, grateful, and affectionate servant and friend.",
            "— I beg to remain, in all respect, esteem, and gratitude, yours most obediently.",
            "— I am, dear sir, with every good wish and sincere regard, your faithful servant.",
            "— Pray accept my humble and renewed assurances of profound respect and esteem.",
            "— I remain, with every consideration, gratitude, and good wish, yours truly and faithfully.",
            "— With every sentiment of respectful admiration, gratitude, and sincere attachment.",
            "— Believe me, my dear friend, ever yours with the most profound affection and esteem.",
            "— I beg to remain, your most devoted, respectful, grateful, and obliged servant.",
            "— I am, very truly, sincerely, and respectfully, your faithful and obliged friend.",
            "— Pray forgive this apparent presumption and liberty I have ventured to take.",
            "— I remain, with every feeling of esteem, gratitude, and sincere regard, yours faithfully.",
            "— With every apology for troubling you with this communication.",
            "— Believe me, ever your respectful, grateful, affectionate, and devoted servant.",
            "— I beg to remain, with profound respect, gratitude, and esteem, yours most sincerely.",
            "— I am, dear madam, with every consideration and sentiment of regard, your devoted servant.",
            "— Pray accept my renewed expressions of profound gratitude and respectful esteem.",
            "— I remain, in all sincerity, respect, and grateful regard, yours truly and obediently.",
            "— With every feeling of sincere respect, gratitude, and affectionate friendship.",
            "— Believe me, dear sir, ever yours with the most sincere respect, esteem, and affection.",
            "— I beg to remain, your most respectful, grateful, faithful, and devoted servant and friend.",
            "— I am, with every good wish, sincere regard, and profound respect, your obliged servant.",
            "— Pray excuse this apparent intrusion and forwardness I have presumed to exhibit.",
            "— I remain, with every sentiment of profound gratitude, respect, and esteem, yours faithfully.",
            "— With every apology for this liberty and the trouble I have occasioned you.",
            "— Believe me, ever your devoted, respectful, grateful, and affectionate servant and friend.",
            "— I beg to remain, in all respect, esteem, gratitude, and sincere regard, yours most obediently.",
            "— I am, dear sir, with every consideration, good wish, and profound respect, your faithful servant.",
            "— Pray accept my humble, renewed, and heartfelt assurances of profound respect and gratitude.",
            "— I remain, with every feeling of sincere gratitude, respect, and affectionate regard, yours truly.",
            "— With every sentiment of respectful admiration, profound gratitude, and sincere attachment.",
            "— Believe me, my dear friend, ever yours with the most profound respect, esteem, and affection.",
            "— I beg to remain, your most devoted, respectful, grateful, faithful, and obliged servant.",
            "— I am, very truly, sincerely, respectfully, and with profound gratitude, your faithful friend.",
            "— Pray forgive this apparent presumption, liberty, and intrusion I have ventured to make.",
            "— I remain, with every consideration, gratitude, esteem, and good wish, yours sincerely and faithfully.",
            "— With every feeling of profound respect, sincere gratitude, and affectionate friendship.",
            "— Believe me, ever your respectful, grateful, affectionate, devoted, and faithful servant and friend.",
            "— I beg to remain, with profound respect, gratitude, esteem, and sincere regard, yours most obediently.",
            "— I am, dear madam, with every sentiment of profound regard, respect, and esteem, your devoted servant.",
            "— Pray accept my renewed, humble, and heartfelt expressions of profound gratitude and respect.",
            "— I remain, in all sincerity, respect, gratitude, and faithful regard, yours truly and obediently.",
            "— With every apology for this communication and the time I have presumed to occupy.",
            "— Believe me, dear sir, ever yours with the most sincere respect, profound esteem, and affection.",
            "— I beg to remain, your most respectful, grateful, faithful, devoted, and obliged servant and friend.",
            "— I am, with every good wish, sincere regard, profound respect, and gratitude, your obliged servant.",
            "— Pray excuse this apparent intrusion, forwardness, and liberty I have presumed to take.",
            "— I remain, with every sentiment of profound gratitude, respect, esteem, and regard, yours faithfully.",
            "— With every feeling of sincere respect, profound gratitude, and affectionate, devoted friendship.",
            "— Believe me, my dear friend, ever yours with the most profound respect, sincere esteem, and affection.",
            "— I beg to remain, in all respect, esteem, gratitude, sincere regard, and faithful service, yours.",
            "— I am, dear sir, with every consideration, profound respect, and sincere good wish, your faithful servant.",
            "— Pray accept my humble, renewed, heartfelt, and profound assurances of respect and gratitude.",
            "— I remain, with every feeling of sincere gratitude, profound respect, and affectionate regard, yours truly.",
            "— With every sentiment of respectful admiration, profound gratitude, sincere attachment, and esteem.",
            "— Believe me, ever your devoted, respectful, grateful, affectionate, faithful, and obliged servant.",
            "— I beg to remain, with profound respect, gratitude, esteem, sincere regard, and faithful service, yours.",
            "— I am, very truly, sincerely, respectfully, with profound gratitude and esteem, your faithful friend.",
            "— Pray forgive this apparent presumption, liberty, intrusion, and forwardness I have made.",
            "— I remain, with every consideration, profound gratitude, esteem, and sincere good wish, yours faithfully.",
            "— With every feeling of profound respect, sincere gratitude, affectionate friendship, and devoted regard.",
            "— Believe me, dear madam, ever yours with the most profound respect, sincere esteem, and affection.",
            "— I beg to remain, your most respectful, grateful, faithful, devoted, affectionate, and obliged servant.",
            "— I am, dear sir, with every sentiment of profound regard, respect, esteem, and gratitude, your servant.",
            "— Pray accept my renewed, humble, heartfelt, and profound expressions of gratitude and respect.",
            "— I remain, in all sincerity, profound respect, gratitude, and faithful regard, yours truly and obediently.",
            "— With every apology for this communication, the liberty taken, and time occupied.",
            "— Believe me, my dear friend, ever yours with the most sincere respect, profound esteem, and affection.",
            "— I beg to remain, with profound respect, gratitude, esteem, sincere regard, and devoted service, yours.",
            "— I am, with every good wish, sincere regard, profound respect, gratitude, and esteem, your servant.",
            "— Pray excuse this apparent intrusion, forwardness, liberty, and presumption I have exhibited.",
            "— I remain, with every sentiment of profound gratitude, respect, esteem, regard, and faithful service, yours.",
            "— With every feeling of sincere respect, profound gratitude, affectionate, devoted, and faithful friendship.",
            "— Believe me, ever your respectful, grateful, affectionate, devoted, faithful, and obliged servant.",
            "— I beg to remain, in all respect, esteem, gratitude, sincere regard, faithful service, and devotion, yours.",
            "— I am, dear madam, with every consideration, profound respect, sincere good wish, and esteem, yours.",
            "— Pray accept my humble, renewed, heartfelt, profound, and sincere assurances of respect and gratitude.",
            "— I remain, with every feeling of sincere gratitude, profound respect, esteem, and affectionate regard, yours.",
            "— With every sentiment of respectful admiration, profound gratitude, sincere attachment, esteem, and regard.",
            "— Believe me, dear sir, ever yours with the most profound respect, sincere esteem, affection, and gratitude.",
            "— I beg to remain, your most respectful, grateful, faithful, devoted, affectionate, obliged, and true servant.",
            "— I am, very truly, sincerely, respectfully, with profound gratitude, esteem, and regard, your faithful friend.",
            "— Pray forgive this apparent presumption, liberty, intrusion, forwardness, and trouble I have caused.",
            "— I remain, with every consideration, profound gratitude, esteem, sincere regard, and good wish, yours faithfully.",
            "— With every feeling of profound respect, sincere gratitude, affectionate friendship, devoted regard, and esteem.",
            "— Believe me, my dear friend, ever yours with the most sincere respect, profound esteem, affection, and gratitude.",
            "— I beg to remain, with profound respect, gratitude, esteem, sincere regard, faithful service, and devotion, yours.",
            "— I am, dear sir, with every sentiment of profound regard, respect, esteem, gratitude, and good wish, your servant.",
            "— Pray accept my renewed, humble, heartfelt, profound, sincere, and grateful expressions of respect.",
            "— I remain, in all sincerity, profound respect, gratitude, faithful regard, and devoted service, yours truly.",
            "— With every apology for this communication, the liberty, intrusion, and time I have presumed to occupy.",
            "— Believe me, ever your devoted, respectful, grateful, affectionate, faithful, obliged, and true servant and friend.",
            "— I beg to remain, with profound respect, gratitude, esteem, sincere regard, faithful service, devotion, and affection, yours.",
            "— I am, with every good wish, sincere regard, profound respect, gratitude, esteem, and faithful service.",
      
