/**
 * The Alchemist's Quill — Application Logic
 * Conjured by Abiud Keter & Kimi
 * Now with Gen Z Slang 🧢
 */

const transmutations = {
    shakespeare: {
        greetings: {
            "hello": "Hail",
            "hi": "Hark",
            "hey": "Ho there",
            "good morning": "Good morrow",
            "good night": "Good e'en",
            "how are you": "How fares thee",
            "thank you": "I give thee thanks",
            "please": "Prithee",
            "sorry": "I do beseech thy pardon",
            "yes": "Aye",
            "no": "Nay",
            "goodbye": "Farewell",
            "love": "love most true",
            "friend": "companion dear",
            "money": "coin",
            "work": "toil",
            "happy": "most glad",
            "sad": "heavy of heart",
            "angry": "wroth",
            "beautiful": "fair",
            "ugly": "ill-favored"
        },
        suffixes: ["— dost thou comprehend?", "— pray, tell me true.", "— by my troth!", "— what sayest thou?", "."],
        prefixes: ["Hark! ", "O! ", "Pray, ", "Mark me: ", "List! "]
    },
    
    victorian: {
        greetings: {
            "hello": "How do you do",
            "hi": "I bid you good day",
            "love": "affection most profound",
            "friend": "dearest acquaintance",
            "money": "pecuniary resources",
            "work": "occupation",
            "happy": "in good spirits",
            "sad": "rather low",
            "beautiful": "quite becoming",
            "ugly": "unfortunate in appearance"
        },
        suffixes: ["— I remain, etc.", "— Most sincerely.", "— Your humble servant.", "."],
        prefixes: ["I daresay ", "It is my understanding that ", "One finds that ", "It is quite the thing to say that "]
    },
    
    poe: {
        greetings: {
            "hello": "Dark greetings",
            "hi": "Hark, from the shadow",
            "love": "obsession eternal",
            "friend": "fellow traveler in darkness",
            "money": "cursed gold",
            "work": "endless toil",
            "happy": "fleeting moment of light",
            "sad": "abyssal despair",
            "beautiful": "hauntingly lovely",
            "ugly": "twisted by sorrow"
        },
        suffixes: ["— nevermore.", "— in the shadows of the night.", "— till the raven calls.", "— through the mists of time.", "."],
        prefixes: ["Once upon a midnight dreary, ", "In the bleak December, ", "From out the shadow, ", "Hark! "]
    },
    
    romantic: {
        greetings: {
            "hello": "Dearest salutations",
            "hi": "My heart leaps",
            "love": "passion unbound",
            "friend": "kindred spirit",
            "money": "earthly means",
            "work": "noble pursuit",
            "happy": "swept by joy",
            "sad": "tears adrift",
            "beautiful": "transcendent",
            "ugly": "unseen by loving eyes"
        },
        suffixes: ["— my heart swells!", "— forever thine.", "— until the stars fade.", "— with all my soul.", "."],
        prefixes: ["Oh! ", "Behold! ", "My dearest, ", "In rapture, "]
    },

    genz: {
        greetings: {
            "hello": "yo",
            "hi": "hey bestie",
            "hey": "hiiii",
            "good morning": "rise and grind",
            "good night": "gn bestie",
            "how are you": "what's the vibe",
            "thank you": "slay, thanks",
            "please": "pls pls",
            "sorry": "my bad bestie",
            "yes": "yasss",
            "no": "nah fam",
            "goodbye": "peace out",
            "love": "simping for",
            "friend": "bestie",
            "money": "bag",
            "work": "the grind",
            "happy": "living my best life",
            "sad": "in my feels",
            "angry": "pressed",
            "beautiful": "ate and left no crumbs",
            "ugly": "mid",
            "cool": "fire",
            "awesome": "slay",
            "bad": "sus",
            "suspicious": "sus",
            "amazing": "iconic",
            "funny": "I'm dead",
            "laughing": "lololol",
            "serious": "no cap",
            "lying": "cap",
            "true": "facts",
            "agree": "periodt",
            "excited": "vibing",
            "tired": "lowkey exhausted",
            "hungry": "need a snack break",
            "bored": "this ain't it",
            "confused": "lost the plot",
            "understand": "I feel you",
            "good": "bussin",
            "food": "grub",
            "outfit": "fit",
            "picture": "pic",
            "selfie": "selfie check",
            "video": "TikTok",
            "music": "vibes",
            "party": "function",
            "alcohol": "drinks",
            "drunk": "wasted",
            "high": "zooted",
            "crazy": "unhinged",
            "obsessed": "down bad",
            "jealous": "big mad",
            "embarrassed": "cringe",
            "awkward": "ick",
            "attractive": "fine af",
            "dating": "talking stage",
            "relationship": "situationship",
            "breakup": "it's giving over",
            "single": "thriving solo",
            "texting": "sliding into DMs",
            "ignore": "ghosting",
            "block": "canceled",
            "popular": "main character energy",
            "unpopular": "NPC behavior",
            "rich": "boujee",
            "poor": "broke bestie",
            "expensive": "giving luxury",
            "cheap": "giving Shein",
            "fast": "speed run",
            "slow": "glazing",
            "easy": "light work",
            "hard": "trying so hard rn",
            "win": "secured the bag",
            "lose": "took an L",
            "fight": "throwing hands",
            "argue": "beefing",
            "gossip": "tea",
            "secret": "spill the tea",
            "news": "what's the tea",
            "trending": "viral",
            "famous": "TikTok famous",
            "unknown": "underground",
            "old": "ancient",
            "young": "fresh",
            "parent": "the rents",
            "mother": "mother (respectfully)",
            "father": "big man",
            "sibling": "sib",
            "child": "tiny human",
            "dog": "doggo",
            "cat": "catto",
            "good job": "you ate that up",
            "congratulations": "so proud bestie",
            "impressive": "that's fire",
            "shocking": "plot twist",
            "expected": "predictable af",
            "boring": "basic",
            "interesting": "serving content",
            "weird": "giving unhinged",
            "normal": "giving vanilla",
            "smart": "big brain",
            "stupid": "smooth brain",
            "brave": "main character energy",
            "scared": "shook",
            "surprised": "wait what",
            "disappointed": "this ain't it chief",
            "proud": "we stan",
            "annoyed": "big yikes",
            "worried": "stressed bestie",
            "relaxed": "chill mode activated",
            "busy": "booked and busy",
            "free": "open to hang",
            "late": "running on TikTok time",
            "early": "that girl",
            "now": "rn",
            "later": "catch you on the flip",
            "never": "not in this economy",
            "always": "24/7",
            "sometimes": "lowkey",
            "maybe": "idk bestie",
            "definitely": "100%",
            "probably": "most likely yes",
            "actually": "lowkey",
            "literally": "literally cannot",
            "seriously": "no joke",
            "joking": "jk bestie",
            "obviously": "obvi",
            "definitely not": "big no",
            "absolutely": "absolutely bestie",
            "totally": "totally vibing",
            "completely": "fully",
            "partially": "kinda sorta",
            "mostly": "mainly",
            "slightly": "a little bit",
            "extremely": "unhinged levels",
            "very": "mad",
            "really": "fr fr",
            "truly": "on god",
            "actually": "fr",
            "honestly": "ngl",
            "frankly": "real talk",
            "basically": "lowkey",
            "essentially": "at the end of the day",
            "practically": "basically",
            "virtually": "basically",
            "almost": "close bestie",
            "nearly": "almost there",
            "about": "around",
            "approximately": "like",
            "exactly": "precisely bestie",
            "precisely": "exactly",
            "specifically": "specifically speaking",
            "generally": "generally speaking",
            "usually": "usually bestie",
            "normally": "normally yes",
            "typically": "typically bestie",
            "frequently": "all the time",
            "often": "often bestie",
            "sometimes": "sometimes bestie",
            "occasionally": "here and there",
            "rarely": "rarely bestie",
            "seldom": "basically never",
            "never": "not happening",
            "always": "always bestie",
            "constantly": "24/7 bestie",
            "continuously": "nonstop",
            "repeatedly": "again and again",
            "regularly": "on the reg",
            "daily": "every day bestie",
            "weekly": "every week bestie",
            "monthly": "every month bestie",
            "yearly": "every year bestie",
            "forever": "until the end of time bestie",
            "permanently": "forever and always",
            "temporarily": "for now bestie",
            "briefly": "real quick",
            "momentarily": "one sec",
            "instantly": "immediately bestie",
            "immediately": "right now bestie",
            "quickly": "speed run",
            "slowly": "taking forever",
            "suddenly": "out of nowhere",
            "gradually": "slowly but surely",
            "eventually": "sooner or later",
            "finally": "finally bestie",
            "initially": "at first",
            "originally": "originally bestie",
            "previously": "before this",
            "formerly": "back in the day",
            "lately": "recently bestie",
            "recently": "just now",
            "currently": "rn",
            "presently": "right now",
            "simultaneously": "at the same time bestie",
            "concurrently": "same time bestie",
            "subsequently": "after that",
            "afterwards": "after bestie",
            "before": "before bestie",
            "after": "after bestie",
            "during": "while bestie",
            "throughout": "the whole time",
            "within": "inside bestie",
            "inside": "inside bestie",
            "outside": "outside bestie",
            "above": "above bestie",
            "below": "below bestie",
            "over": "over bestie",
            "under": "under bestie",
            "between": "between bestie",
            "among": "among bestie",
            "beside": "next to bestie",
            "near": "close bestie",
            "far": "far bestie",
            "here": "right here",
            "there": "over there",
            "everywhere": "everywhere bestie",
            "somewhere": "somewhere bestie",
            "nowhere": "nowhere bestie",
            "anywhere": "anywhere bestie",
            "elsewhere": "somewhere else",
            "everyone": "everyone bestie",
            "someone": "someone bestie",
            "anyone": "anyone bestie",
            "no one": "literally no one",
            "somebody": "somebody bestie",
            "anybody": "anybody bestie",
            "nobody": "nobody bestie",
            "everybody": "everybody bestie",
            "something": "something bestie",
            "anything": "anything bestie",
            "nothing": "literally nothing",
            "everything": "everything bestie",
            "some": "some bestie",
            "any": "any bestie",
            "no": "no bestie",
            "all": "all bestie",
            "none": "none bestie",
            "both": "both bestie",
            "either": "either bestie",
            "neither": "neither bestie",
            "each": "each bestie",
            "every": "every bestie",
            "other": "other bestie",
            "another": "another bestie",
            "such": "such bestie",
            "what": "what bestie",
            "which": "which bestie",
            "who": "who bestie",
            "whom": "whom bestie",
            "whose": "whose bestie",
            "that": "that bestie",
            "this": "this bestie",
            "these": "these bestie",
            "those": "those bestie",
            "one": "one bestie",
            "two": "two bestie",
            "three": "three bestie",
            "four": "four bestie",
            "five": "five bestie",
            "first": "first bestie",
            "last": "last bestie",
            "next": "next bestie",
            "previous": "previous bestie",
            "following": "following bestie",
            "preceding": "preceding bestie",
            "subsequent": "subsequent bestie",
            "prior": "prior bestie",
            "former": "former bestie",
            "latter": "latter bestie",
            "beginning": "beginning bestie",
            "start": "start bestie",
            "middle": "middle bestie",
            "center": "center bestie",
            "end": "end bestie",
            "conclusion": "conclusion bestie",
            "opening": "opening bestie",
            "closing": "closing bestie",
            "introduction": "intro bestie",
            "preface": "preface bestie",
            "prologue": "prologue bestie",
            "epilogue": "epilogue bestie",
            "chapter": "chapter bestie",
            "section": "section bestie",
            "part": "part bestie",
            "piece": "piece bestie",
            "portion": "portion bestie",
            "segment": "segment bestie",
            "fragment": "fragment bestie",
            "bit": "bit bestie",
            "item": "item bestie",
            "article": "article bestie",
            "object": "object bestie",
            "thing": "thing bestie",
            "stuff": "stuff bestie",
            "matter": "matter bestie",
            "material": "material bestie",
            "substance": "substance bestie",
            "element": "element bestie",
            "component": "component bestie",
            "ingredient": "ingredient bestie",
            "factor": "factor bestie",
            "aspect": "aspect bestie",
            "feature": "feature bestie",
            "characteristic": "characteristic bestie",
            "quality": "quality bestie",
            "property": "property bestie",
            "attribute": "attribute bestie",
            "trait": "trait bestie",
            "nature": "nature bestie",
            "type": "type bestie",
            "kind": "kind bestie",
            "sort": "sort bestie",
            "variety": "variety bestie",
            "class": "class bestie",
            "category": "category bestie",
            "group": "group bestie",
            "set": "set bestie",
            "series": "series bestie",
            "collection": "collection bestie",
            "assembly": "assembly bestie",
            "gathering": "gathering bestie",
            "meeting": "meeting bestie",
            "conference": "conference bestie",
            "convention": "convention bestie",
            "assembly": "assembly bestie",
            "crowd": "crowd bestie",
            "audience": "audience bestie",
            "spectators": "spectators bestie",
            "onlookers": "onlookers bestie",
            "bystanders": "bystanders bestie",
            "witnesses": "witnesses bestie",
            "participants": "participants bestie",
            "members": "members bestie",
            "associates": "associates bestie",
            "colleagues": "colleagues bestie",
            "peers": "peers bestie",
            "equals": "equals bestie",
            "rivals": "rivals bestie",
            "opponents": "opponents bestie",
            "enemies": "enemies bestie",
            "adversaries": "adversaries bestie",
            "competitors": "competitors bestie",
            "contestants": "contestants bestie",
            "candidates": "candidates bestie",
            "nominees": "nominees bestie",
            "applicants": "applicants bestie",
            "candidates": "candidates bestie",
            "hopefuls": "hopefuls bestie",
            "aspirants": "aspirants bestie",
            "seekers": "seekers bestie",
            "searchers": "searchers bestie",
            "hunters": "hunters bestie",
            "pursuers": "pursuers bestie",
            "chasers": "chasers bestie",
            "followers": "followers bestie",
            "fans": "fans bestie",
            "supporters": "supporters bestie",
            "backers": "backers bestie",
            "sponsors": "sponsors bestie",
            "patrons": "patrons bestie",
            "benefactors": "benefactors bestie",
            "donors": "donors bestie",
            "contributors": "contributors bestie",
            "helpers": "helpers bestie",
            "assistants": "assistants bestie",
            "aides": "aides bestie",
            "deputies": "deputies bestie",
            "proxies": "proxies bestie",
            "substitutes": "substitutes bestie",
            "replacements": "replacements bestie",
            "alternatives": "alternatives bestie",
            "options": "options bestie",
            "choices": "choices bestie",
            "selections": "selections bestie",
            "picks": "picks bestie",
            "preferences": "preferences bestie",
            "favorites": "favorites bestie",
            "likes": "likes bestie",
            "loves": "loves bestie",
            "enjoys": "enjoys bestie",
            "appreciates": "appreciates bestie",
            "values": "values bestie",
            "treasures": "treasures bestie",
            "cherishes": "cherishes bestie",
            "prizes": "prizes bestie",
            "esteems": "esteems bestie",
            "respects": "respects bestie",
            "honors": "honors bestie",
            "reveres": "reveres bestie",
            "worships": "worships bestie",
            "adores": "adores bestie",
            "idolizes": "idolizes bestie",
            "admires": "admires bestie",
            "looks up to": "looks up to bestie",
            "emulates": "emulates bestie",
            "imitates": "imitates bestie",
            "copies": "copies bestie",
            "mimics": "mimics bestie",
            "parrots": "parrots bestie",
            "echoes": "echoes bestie",
            "reflects": "reflects bestie",
            "mirrors": "mirrors bestie",
            "represents": "represents bestie",
            "symbolizes": "symbolizes bestie",
            "signifies": "signifies bestie",
            "means": "means bestie",
            "denotes": "denotes bestie",
            "indicates": "indicates bestie",
            "suggests": "suggests bestie",
            "implies": "implies bestie",
            "hints": "hints bestie",
            "infers": "infers bestie",
            "deduces": "deduces bestie",
            "concludes": "concludes bestie",
            "determines": "determines bestie",
            "decides": "decides bestie",
            "resolves": "resolves bestie",
            "settles": "settles bestie",
            "fixes": "fixes bestie",
            "establishes": "establishes bestie",
            "institutes": "institutes bestie",
            "creates": "creates bestie",
            "makes": "makes bestie",
            "produces": "produces bestie",
            "generates": "generates bestie",
            "forms"
